### PR TITLE
Prac 5 code review request

### PR DESCRIPTION
**Pull request by j-finger**
Please check formatting, naming and logic @Michael-E-JCU

### CODE REVIEW

**Comment by Michael-E-JCU** [comment]
https://github.com/j-finger/CP1404_practicals/blob/856eea3be0c0d253d5992f0c29ddab2ffd18849a/prac_05/emails.py#L12-L15

**Comment by ghost** [comment]
https://github.com/j-finger/CP1404_practicals/blob/856eea3be0c0d253d5992f0c29ddab2ffd18849a/prac_05/emails.py#L12-L15
I don't believe this what part of the task, although I'm not sure there's a problem with doing extra work.

**Comment by ghost** [comment]
https://github.com/j-finger/CP1404_practicals/blob/856eea3be0c0d253d5992f0c29ddab2ffd18849a/prac_05/emails.py#L20
The user_name variable may need a better name.

**Comment by ghost** [comment]
https://github.com/j-finger/CP1404_practicals/blob/856eea3be0c0d253d5992f0c29ddab2ffd18849a/prac_05/state_names.py#L8
Leftover from testing I assume 🧪

**Comment by ghost** [comment]
https://github.com/j-finger/CP1404_practicals/blob/856eea3be0c0d253d5992f0c29ddab2ffd18849a/prac_05/hex_colours.py#L6
Odd space in one of the values.

**Comment by ghost** [comment]
https://github.com/j-finger/CP1404_practicals/blob/feedback/prac_05/word_occurrences.py#L5-L21
I don't believe this actually counts the frequency of words in the sentence, you may want to refer to the solution for help. 
https://github.com/CP1404/Practicals/blob/solutions/prac_05/word_occurrences.py

**Comment by ghost** [comment]
Other than word_occurences, I think you've done well. I like the variable names and the code is readable.

**Comment by j-finger** [comment]
> https://github.com/j-finger/CP1404_practicals/blob/feedback/prac_05/word_occurrences.py#L5-L21
> I don't believe this actually counts the frequency of words in the sentence, you may want to refer to the solution for help.
> https://github.com/CP1404/Practicals/blob/solutions/prac_05/word_occurrences.py

From my testing, it seems to work correctly, other than that, thanks for the feedback @Michael-E-JCU ! :)

**Pull request merged**
